project:
  type: website
  output-dir: docs

website:
  title: "math-437-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Project2.qmd
        text: Project

format:
  html:
    backgroundcolor: "#eeffee"
    fontcolor: "darkgreen"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



