project:
  type: website
  output-dir: docs

website:
  title: "math-437-portfolio"
  navbar:
    background: "#1f3a5f"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Project2.qmd
        text: Project

format:
  html:
    backgroundcolor: "#f7efe5"
    fontcolor: "#1f3a5f"
    linkcolor: "#e67e22"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



